[build]
  command = "yarn build"
  functions = "lambda/functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/repo-card"
  to = "/.netlify/functions/repo-card"
  status = 200
[[redirects]]
  from = "/computer"
  to = "/.netlify/functions/computer"
  status = 200
[[redirects]]
  from = "/package-card"
  to = "/.netlify/functions/package-card"
  status = 200